version: '3'

services:
  server:
    build: ./server
    command: sh -c "npm run build && npm run start"
    expose:
      - 4000
    environment:
      - NODE_ENV=production
    depends_on:
      - mongodb
  client:
    build: ./client
    command: sh -c "npm run build"
    volumes:
      - web-client-build:/app/build
    environment:
      - NODE_ENV=production
      - REACT_APP_GRAPHQL_ENDPOINT=http://localhost:${GATEWAY_PORT}/graphql  
  mongodb:
    image: mongo:5.0.3
  nginx:
    image: nginx:1.21.3
    depends_on:
      - server
      - client
    restart: always
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - web-client-build:/web-client-build
volumes:
  web-client-build: